{% set name = "pythonanywhere-core" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythonanywhere_core-{{ version }}.tar.gz
    sha256: 40fcef8efc31ccc5478a41305ce96abec2eabe532d549bc04787328d46519a3a

  # tests and tests data files
  - url: https://github.com/{{ name.split('-')[0] }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: ff0ccf5c350eea9c04147b307634749286e9f0f86a2d01ee879a14473fd47c89
    folder: gh_src

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - poetry-core >=1.0.0
    - pip
  run:
    - python
    - python-dateutil >=2.8.2,<3.0
    - requests >=2.30.0,<3.0
    - snakesay >=0.10.3,<0.11.0
    - typing_extensions >=4.5.0,<5.0

# Skip test with error on path Windows Path/os.path
# AssertionError: assert {'url': '/static/', 'path': '\\project\\path\\static'} 
# == {'url': '/static/', 'path': '/project/path/static'}
{% set skip_broken_tests = [
    "test_raises_if_post_returns_a_200_with_status_error",
    "test_raises_if_post_does_not_20x_that_is_not_a_cname_error",
    "test_does_not_raise_if_post_responds_with_a_cname_error",
    "test_raises_with_api_error_message_for_any_other_error",
    "test_does_two_posts_to_static_files_endpoint"
] %}

test:
  source_files:
    - gh_src/tests
  requires:
    - pip
    - pytest >=8.0.0,<9
    - pytest-mock >=3.10.0,<4.0
    - responses >=0.25.0,<1.0
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest gh_src/tests -vv --color=yes  # [not win]
    - pytest gh_src/tests -vv --color=yes -k "not ({{ skip_broken_tests | join(' or ') }})"  # [win]
  imports:
    - pythonanywhere_core
    - pythonanywhere_core.base
    - pythonanywhere_core.exceptions
    - pythonanywhere_core.files
    - pythonanywhere_core.schedule
    - pythonanywhere_core.students
    - pythonanywhere_core.webapp
    - pythonanywhere_core.website

about:
  home: https://github.com/pythonanywhere/pythonanywhere-core
  dev_url: https://github.com/pythonanywhere/pythonanywhere-core
  doc_url: https://github.com/pythonanywhere/pythonanywhere-core/tree/master/docs
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: API wrapper for programmatic management of PythonAnywhere services
  description: It's an extraction and improvement of core code behind PythonAnywhere cli tool

extra:
  skip-lints:
    - patch_unnecessary
