{% set name = "pythonanywhere-core" %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
    sha256: 61812c51f15f02921a68705df7e4c956ceb5b16f4c0e3c6ba9ca1a55119bf22a
  - url: https://github.com/{{ name.split('-')[0] }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e5c1cccad507cd1ae2a1370e50c934f891ba920a819350cf72f4ce8017616b3d
    folder: gh_src

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - python
    - python-dateutil >=2.8.2,<3.0
    - requests >=2.30.0,<3.0
    - typing_extensions >=4.5.0,<5.0

{% set deselect_tests = "" %}
# OSError: [WinError 1314] A required privilege is not held by the client
{% set deselect_tests = deselect_tests + " --deselect=gh_src/tests/test_webapp.py::test_nuke_option_overrides_all_but_token_check" %}  # [win]

test:
  source_files:
    - gh_src/tests
  requires:
    - pip
    - pytest >=8.0.0,<9
    - pytest-mock >=3.10.0,<4.0
    - responses >=0.25.0,<0.26
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest gh_src/tests -vv --color=yes {{ deselect_tests }}
  imports:
    - pythonanywhere_core
    - pythonanywhere_core.base
    - pythonanywhere_core.exceptions
    - pythonanywhere_core.files
    - pythonanywhere_core.schedule
    - pythonanywhere_core.students
    - pythonanywhere_core.webapp
    - pythonanywhere_core.website

about:
  home: https://github.com/pythonanywhere/pythonanywhere-core
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: API wrapper for programmatic management of PythonAnywhere services
  description: It's an extraction and improvement of core code behind PythonAnywhere cli tool
  dev_url: https://github.com/pythonanywhere/pythonanywhere-core
  doc_url: https://github.com/pythonanywhere/pythonanywhere-core/tree/master/docs

